export { PlumeEditor } from './PlumeEditor'
export type { PlumeEditorProps } from './PlumeEditor'
export { Toolbar } from './Toolbar'
export type { ToolbarProps } from './Toolbar'
export { ToolbarButton } from './ToolbarButton'
export type { ToolbarButtonProps } from './ToolbarButton'
export { ToolbarDropdown } from './ToolbarDropdown'
export type { ToolbarDropdownProps } from './ToolbarDropdown'
export { ToolbarLink } from './ToolbarLink'
export type { ToolbarLinkProps } from './ToolbarLink'
export { PasteModal } from './PasteModal'
export type { PasteModalProps } from './PasteModal'
export { usePlumeEditor } from './usePlumeEditor'

export { EditorContent } from '@tiptap/react'
export type { Editor } from '@tiptap/react'
export type { PlumeOptions, ToolbarConfig, ToolbarItem, ToolbarItemName } from '@useplume/core'
